# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5449fe4c5c77cdbb2bd4fa8d13cd949787d7b2f9247fa4fae517f1100bbc406c70ab4fe954d3750596a5a975946fd157c8ee90598e7267f7989bfa320255743a

test:
  secret_key_base: 8495de87a6700faf7651c87e8149e85786626ac05db38b3dd8db8428552639a5aae798804b8da33d6d36ec5ee08c25dc139865c8c1bbfea68f0298603646fcf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
